export const ADD_FORMATION =  "ADD_FORMATION";
export const DELETE_FORMATION = "DELETE_FORMATION";
export const EDIT_FORMATION = "EDIT_FORMATION";

export const ADD_EXPERIENCES =  "ADD_EXPERIENCES";
export const DELETE_EXPERIENCES = "DELETE_EXPERIENCES";
export const EDIT_EXPERIENCES = "EDIT_EXPERIENCES";

export const ADD_COMPETENCES =  "ADD_COMPETENCES";
export const DELETE_COMPETENCES = "DELETE_COMPETENCES";
export const EDIT_COMPETENCES = "EDIT_COMPETENCES";




